/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewsIndexRouteImport } from './routes/previews/index'
import { Route as PreviewsIdentifierRouteImport } from './routes/previews/$identifier'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewsIndexRoute = PreviewsIndexRouteImport.update({
  id: '/previews/',
  path: '/previews/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewsIdentifierRoute = PreviewsIdentifierRouteImport.update({
  id: '/previews/$identifier',
  path: '/previews/$identifier',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/previews/$identifier': typeof PreviewsIdentifierRoute
  '/previews': typeof PreviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/previews/$identifier': typeof PreviewsIdentifierRoute
  '/previews': typeof PreviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/previews/$identifier': typeof PreviewsIdentifierRoute
  '/previews/': typeof PreviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/previews/$identifier' | '/previews'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/previews/$identifier' | '/previews'
  id: '__root__' | '/' | '/previews/$identifier' | '/previews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreviewsIdentifierRoute: typeof PreviewsIdentifierRoute
  PreviewsIndexRoute: typeof PreviewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/previews/': {
      id: '/previews/'
      path: '/previews'
      fullPath: '/previews'
      preLoaderRoute: typeof PreviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/previews/$identifier': {
      id: '/previews/$identifier'
      path: '/previews/$identifier'
      fullPath: '/previews/$identifier'
      preLoaderRoute: typeof PreviewsIdentifierRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreviewsIdentifierRoute: PreviewsIdentifierRoute,
  PreviewsIndexRoute: PreviewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
